# Generated by Django 5.0.1 on 2024-02-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Journal",
            new_name="JournalEntry",
        ),
        migrations.RenameField(
            model_name="plant",
            old_name="source_url",
            new_name="link",
        ),
        migrations.AlterField(
            model_name="plant",
            name="img_height",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="image height"
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="img_width",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="image width"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task",
            field=models.CharField(
                choices=[
                    (0, "weed"),
                    (1, "water"),
                    (2, "fertilize"),
                    (3, "start"),
                    (4, "plant"),
                    (5, "other"),
                ],
                max_length=50,
            ),
        ),
    ]
