# Generated by Django 5.0.1 on 2024-02-12 21:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0002_rename_journal_journalentry_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bed",
            old_name="num",
            new_name="bed",
        ),
    ]
