# Generated by Django 5.0.2 on 2024-02-13 02:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_alter_bed_bed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planting',
            old_name='harvest_date',
            new_name='harvest_dt',
        ),
        migrations.RenameField(
            model_name='planting',
            old_name='plant_date',
            new_name='plant_dt',
        ),
        migrations.RenameField(
            model_name='planting',
            old_name='start_date',
            new_name='start_dt',
        ),
        migrations.AddField(
            model_name='plant',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='last_updated',
            field=models.DateField(auto_now=True, verbose_name='last updated'),
        ),
    ]
