# Generated by Django 5.0.2 on 2024-02-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_alter_plant_options_alter_planting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='freq',
            field=models.CharField(choices=[('d', 'daily'), ('w', 'weekly'), ('m', 'monthly'), ('y', 'yearly'), ('o', 'other')], max_length=1, verbose_name='frequency'),
        ),
    ]
