# Generated by Django 5.0.2 on 2024-02-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_alter_task_options_alter_task_freq_alter_task_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(),
        ),
    ]
