# Generated by Django 5.0.2 on 2024-02-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_remove_plant_date_added_remove_plant_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='planting',
            name='harvest_dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planting',
            name='plant_dt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
