# Generated by Django 5.0.2 on 2024-02-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_alter_journalentry_options_alter_planting_harvest_dt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bed',
            options={'ordering': ['bed']},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date'], 'verbose_name': 'journal entry', 'verbose_name_plural': 'journal entries'},
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
