# Generated by Django 5.0.1 on 2024-02-15 22:19

import recurrence.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0012_remove_task_freq_alter_journalentry_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="freq",
            field=recurrence.fields.RecurrenceField(blank=True, null=True),
        ),
    ]
