# Generated by Django 5.0.1 on 2024-02-25 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0013_task_freq'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='harvest_dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.plant'),
        ),
        migrations.AddField(
            model_name='bed',
            name='plant_dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='row',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='start_dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='bed',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (0, 'Starts')], unique=True, verbose_name='bed number'),
        ),
    ]
