# Generated by Django 5.0.1 on 2024-02-26 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0014_bed_count_bed_harvest_dt_bed_plant_bed_plant_dt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='count',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='harvest_dt',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='plant_dt',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='row',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='start_dt',
        ),
        migrations.AlterField(
            model_name='bed',
            name='bed',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (0, 'Starts')], verbose_name='bed number'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plants.task'),
        ),
    ]
