# Generated by Django 5.0.1 on 2024-02-27 06:33

import django.db.models.deletion
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0015_remove_bed_count_remove_bed_harvest_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='img_height', null=True, upload_to='', width_field='img_width'),
        ),
        migrations.AlterField(
            model_name='planting',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plants.bed'),
        ),
        migrations.AlterField(
            model_name='planting',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plants.plant'),
        ),
    ]
