# Generated by Django 5.0.1 on 2024-02-27 10:22

import django.db.models.deletion
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0016_alter_plant_image_alter_planting_bed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='entry',
            new_name='note',
        ),
        migrations.AddField(
            model_name='bed',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='img_height', null=True, upload_to='', verbose_name='current image', width_field='img_width'),
        ),
        migrations.AddField(
            model_name='bed',
            name='img_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='image height'),
        ),
        migrations.AddField(
            model_name='bed',
            name='img_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='image width'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plants.bed'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='image_desc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plants.task'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='max_germ_days',
            field=models.IntegerField(verbose_name='max days to germinate'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='max_maturity_days',
            field=models.IntegerField(verbose_name='max days to maturity'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='min_germ_days',
            field=models.IntegerField(verbose_name='min days to germinate'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='min_maturity_days',
            field=models.IntegerField(verbose_name='min days to maturity'),
        ),
        migrations.AlterField(
            model_name='planting',
            name='harvest_dt',
            field=models.DateField(blank=True, null=True, verbose_name='date harvested'),
        ),
        migrations.AlterField(
            model_name='planting',
            name='plant_dt',
            field=models.DateField(blank=True, null=True, verbose_name='date planted'),
        ),
        migrations.AlterField(
            model_name='planting',
            name='start_dt',
            field=models.DateField(verbose_name='date started'),
        ),
    ]
