# Generated by Django 5.0.1 on 2024-03-02 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0020_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
