# Generated by Django 5.0.1 on 2024-03-03 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0022_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['task']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
    ]
