# Generated by Django 5.0.1 on 2024-03-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0023_delete_events_alter_task_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JournalEntry',
            new_name='JournalNote',
        ),
        migrations.AlterModelOptions(
            name='bed',
            options={'ordering': ['num']},
        ),
        migrations.AlterModelOptions(
            name='journalnote',
            options={'ordering': ['-date'], 'verbose_name': 'journal note', 'verbose_name_plural': 'journal notes'},
        ),
        migrations.RenameField(
            model_name='bed',
            old_name='bed',
            new_name='num',
        ),
        migrations.AddField(
            model_name='task',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='interval',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
