# Generated by Django 5.0.1 on 2024-03-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0024_rename_journalentry_journalnote_alter_bed_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='interval',
        ),
        migrations.AddField(
            model_name='task',
            name='period',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=255, null=True, verbose_name='period'),
        ),
        migrations.AlterField(
            model_name='task',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='iterations per period)'),
        ),
    ]
