# Generated by Django 5.0.1 on 2024-03-03 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0026_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='events',
            name='end',
        ),
        migrations.RemoveField(
            model_name='events',
            name='start',
        ),
        migrations.AddField(
            model_name='events',
            name='end_recur',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plants.task'),
        ),
        migrations.AddField(
            model_name='events',
            name='start_recur',
            field=models.DateField(blank=True, null=True),
        ),
    ]
