# Generated by Django 5.0.1 on 2024-03-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0028_rename_end_recur_events_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='count',
        ),
        migrations.RemoveField(
            model_name='task',
            name='period',
        ),
        migrations.AddField(
            model_name='task',
            name='days_of_week',
            field=models.CharField(blank=True, choices=[('0', 'Sunday'), ('1', 'Moonday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], max_length=255, null=True, verbose_name='day(s) of week'),
        ),
        migrations.AddField(
            model_name='task',
            name='end_recur',
            field=models.DateField(blank=True, null=True, verbose_name='Last occurrence'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_recurring',
            field=models.BooleanField(default=True, verbose_name='repeating'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_recur',
            field=models.DateField(blank=True, null=True, verbose_name='First occurrnce'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255, verbose_name='task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='start date'),
        ),
    ]
