# Generated by Django 5.0.1 on 2024-03-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0029_remove_task_count_remove_task_period_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.AlterField(
            model_name='task',
            name='days_of_week',
            field=models.CharField(blank=True, choices=[('0', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], max_length=255, null=True, verbose_name='day(s) of week'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_recur',
            field=models.DateField(blank=True, null=True, verbose_name='First occurrence'),
        ),
    ]
