# Generated by Django 5.0.1 on 2024-03-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0030_delete_events_alter_task_days_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='days_of_week',
            field=models.CharField(blank=True, choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], max_length=15, null=True, verbose_name='day(s) of week'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_recur',
            field=models.DateField(blank=True, null=True, verbose_name='last occurrence'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255, verbose_name='task/chore'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_recur',
            field=models.DateField(blank=True, null=True, verbose_name='first occurrence'),
        ),
    ]
