# Generated by Django 5.0.1 on 2024-03-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0031_alter_task_days_of_week_alter_task_end_recur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='is complete'),
        ),
    ]
